target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'composeApp', :path => '../composeApp', :modular_headers => true
    pod 'TensorFlowLiteObjC'
    pod 'TensorFlowLiteObjC/Metal'
    pod 'TensorFlowLiteObjC/CoreML'
end